# Generated by Django 5.2.12 on 2026-03-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('base', models.CharField(max_length=100)),
                ('founded', models.IntegerField()),
                ('team_principal', models.CharField(max_length=100)),
                ('engine_supplier', models.CharField(max_length=50)),
                ('championships', models.IntegerField(default=0)),
                ('team_color', models.CharField(default='#e10600', max_length=7)),
                ('bio', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/')),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='teams/cars/')),
                ('garage_image', models.ImageField(blank=True, null=True, upload_to='teams/garage/')),
                ('podium_image', models.ImageField(blank=True, null=True, upload_to='teams/podium/')),
            ],
        ),
    ]
