# Generated by Django 5.2.12 on 2026-03-16 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('drivers_champion', models.CharField(max_length=100)),
                ('constructors_champion', models.CharField(max_length=100)),
                ('total_races', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('season_image', models.ImageField(blank=True, null=True, upload_to='seasons/')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('driver', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('points', models.DecimalField(decimal_places=1, max_digits=6)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.season')),
            ],
        ),
    ]
