# Generated by Django 5.2.12 on 2026-03-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='constructor_champion_image',
            field=models.ImageField(blank=True, null=True, upload_to='seasons/constructors/'),
        ),
        migrations.AddField(
            model_name='season',
            name='driver_champion_image',
            field=models.ImageField(blank=True, null=True, upload_to='seasons/drivers/'),
        ),
    ]
