# Generated by Django 5.2.12 on 2026-03-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('driver_number', models.IntegerField(blank=True, null=True)),
                ('abbreviation', models.CharField(max_length=3)),
                ('races', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('podiums', models.IntegerField(default=0)),
                ('pole_positions', models.IntegerField(default=0)),
                ('fastest_laps', models.IntegerField(default=0)),
                ('championships', models.IntegerField(default=0)),
                ('bio', models.TextField()),
                ('debut_year', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('helmet_image', models.ImageField(blank=True, null=True, upload_to='helmets/')),
            ],
        ),
    ]
