# Generated by Django 5.2.12 on 2026-03-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='action_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/action/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/car/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='podium_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/podium/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='young_career_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/young/'),
        ),
    ]
