# Generated by Django 5.2.12 on 2026-06-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_action_image_driver_car_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='team_color',
            field=models.CharField(default='#e10600', help_text='Use a hex color for the driver/team accent line.', max_length=7),
        ),
        migrations.AddField(
            model_name='driver',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
