# Generated by Django 5.2.12 on 2026-06-25 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_team_color_driver_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTeamPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_color', models.CharField(default='#e10600', help_text='Use a hex color for the team period accent.', max_length=7)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, help_text='Leave empty if the driver is currently with this team.', null=True)),
                ('order', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_periods', to='drivers.driver')),
            ],
            options={
                'ordering': ['start_year', 'order'],
            },
        ),
    ]
