# Generated by Django 5.2.12 on 2026-06-25 05:12

from django.db import migrations


def create_lewis_history(apps, schema_editor):
    Driver = apps.get_model('drivers', 'Driver')
    DriverTeamPeriod = apps.get_model('drivers', 'DriverTeamPeriod')
    try:
        lewis = Driver.objects.get(name__iexact='Lewis Hamilton')
    except Driver.DoesNotExist:
        return

    periods = [
        {'team_name': 'McLaren', 'team_color': '#ff6200', 'start_year': 2007, 'end_year': 2012, 'order': 0},
        {'team_name': 'Mercedes', 'team_color': '#00d2be', 'start_year': 2013, 'end_year': 2024, 'order': 1},
        {'team_name': 'Ferrari', 'team_color': '#dc0000', 'start_year': 2025, 'end_year': None, 'order': 2},
    ]

    for period in periods:
        DriverTeamPeriod.objects.update_or_create(
            driver=lewis,
            team_name=period['team_name'],
            start_year=period['start_year'],
            defaults={
                'team_color': period['team_color'],
                'end_year': period['end_year'],
                'order': period['order'],
            }
        )

    lewis.team_name = 'Ferrari'
    lewis.team_color = '#dc0000'
    lewis.save()


def reverse_lewis_history(apps, schema_editor):
    Driver = apps.get_model('drivers', 'Driver')
    DriverTeamPeriod = apps.get_model('drivers', 'DriverTeamPeriod')
    try:
        lewis = Driver.objects.get(name__iexact='Lewis Hamilton')
    except Driver.DoesNotExist:
        return
    DriverTeamPeriod.objects.filter(driver=lewis, team_name__in=['McLaren', 'Mercedes', 'Ferrari']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driverteamperiod'),
    ]

    operations = [
        migrations.RunPython(create_lewis_history, reverse_lewis_history),
    ]
