# Generated by Django 5.2.12 on 2026-03-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('length_km', models.DecimalField(decimal_places=3, max_digits=5)),
                ('turns', models.IntegerField()),
                ('drs_zones', models.IntegerField()),
                ('first_gp_year', models.IntegerField()),
                ('lap_record_time', models.CharField(blank=True, max_length=20, null=True)),
                ('lap_record_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('lap_record_year', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField()),
                ('track_image', models.ImageField(blank=True, null=True, upload_to='circuits/tracks/')),
                ('aerial_image', models.ImageField(blank=True, null=True, upload_to='circuits/aerial/')),
                ('corner_image', models.ImageField(blank=True, null=True, upload_to='circuits/corners/')),
            ],
        ),
    ]
