# Generated by Django 5.2.12 on 2026-03-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('compound', models.CharField(choices=[('soft', 'Soft'), ('medium', 'Medium'), ('hard', 'Hard'), ('intermediate', 'Intermediate'), ('wet', 'Wet')], max_length=20)),
                ('colour', models.CharField(default='#ffffff', max_length=7)),
                ('description', models.TextField()),
                ('best_used_for', models.CharField(max_length=200)),
                ('average_stint_length', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tyres/')),
            ],
        ),
    ]
