# Generated by Django 5.2.12 on 2026-03-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('driver', 'Driver Record'), ('constructor', 'Constructor Record'), ('race', 'Race Record')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=100)),
                ('holder', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='records/')),
            ],
        ),
    ]
